#!/bin/bash

# VIM
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall

# iTerm

curl -fLo ~/.iterm/gruvbox-dark.itermcolors --create-dirs \
    https://raw.githubusercontent.com/morhetz/gruvbox-contrib/master/iterm2/gruvbox-dark.itermcolors

apm install --packages-file apm-list.txt
