#!/bin/bash

# Install n with latest stable Node and NPM
./install-node

# VIM
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall

# Git Autocomplete

curl -fLo ~/git-completion.bash --create-dirs \
  https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
